// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: router/events.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//
// Emitted when owner address is updated
// @param previous_owner representing the address of the previous owner
// @param new_owner representing the address of the new owner
type OwnerUpdated struct {
	PreviousOwner string `protobuf:"bytes,1,opt,name=previous_owner,json=previousOwner,proto3" json:"previous_owner,omitempty"`
	NewOwner      string `protobuf:"bytes,2,opt,name=new_owner,json=newOwner,proto3" json:"new_owner,omitempty"`
}

func (m *OwnerUpdated) Reset()         { *m = OwnerUpdated{} }
func (m *OwnerUpdated) String() string { return proto.CompactTextString(m) }
func (*OwnerUpdated) ProtoMessage()    {}
func (*OwnerUpdated) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba99373efa5638de, []int{0}
}
func (m *OwnerUpdated) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OwnerUpdated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OwnerUpdated.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OwnerUpdated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnerUpdated.Merge(m, src)
}
func (m *OwnerUpdated) XXX_Size() int {
	return m.Size()
}
func (m *OwnerUpdated) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnerUpdated.DiscardUnknown(m)
}

var xxx_messageInfo_OwnerUpdated proto.InternalMessageInfo

func (m *OwnerUpdated) GetPreviousOwner() string {
	if m != nil {
		return m.PreviousOwner
	}
	return ""
}

func (m *OwnerUpdated) GetNewOwner() string {
	if m != nil {
		return m.NewOwner
	}
	return ""
}

//
// Emitted when an allowed source domain sender is added
// @param domain remote domain
// @param address source domain sender address on domain
type AllowedSourceDomainSenderAdded struct {
	Domain  uint32 `protobuf:"varint,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Address []byte `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *AllowedSourceDomainSenderAdded) Reset()         { *m = AllowedSourceDomainSenderAdded{} }
func (m *AllowedSourceDomainSenderAdded) String() string { return proto.CompactTextString(m) }
func (*AllowedSourceDomainSenderAdded) ProtoMessage()    {}
func (*AllowedSourceDomainSenderAdded) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba99373efa5638de, []int{1}
}
func (m *AllowedSourceDomainSenderAdded) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AllowedSourceDomainSenderAdded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AllowedSourceDomainSenderAdded.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AllowedSourceDomainSenderAdded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllowedSourceDomainSenderAdded.Merge(m, src)
}
func (m *AllowedSourceDomainSenderAdded) XXX_Size() int {
	return m.Size()
}
func (m *AllowedSourceDomainSenderAdded) XXX_DiscardUnknown() {
	xxx_messageInfo_AllowedSourceDomainSenderAdded.DiscardUnknown(m)
}

var xxx_messageInfo_AllowedSourceDomainSenderAdded proto.InternalMessageInfo

func (m *AllowedSourceDomainSenderAdded) GetDomain() uint32 {
	if m != nil {
		return m.Domain
	}
	return 0
}

func (m *AllowedSourceDomainSenderAdded) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

//
// Emitted when a allowed source domain sender is removed
// @param domain remote domain
// @param address source domain sender address on domain
type AllowedSourceDomainSenderRemoved struct {
	Domain  uint32 `protobuf:"varint,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Address []byte `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *AllowedSourceDomainSenderRemoved) Reset()         { *m = AllowedSourceDomainSenderRemoved{} }
func (m *AllowedSourceDomainSenderRemoved) String() string { return proto.CompactTextString(m) }
func (*AllowedSourceDomainSenderRemoved) ProtoMessage()    {}
func (*AllowedSourceDomainSenderRemoved) Descriptor() ([]byte, []int) {
	return fileDescriptor_ba99373efa5638de, []int{2}
}
func (m *AllowedSourceDomainSenderRemoved) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AllowedSourceDomainSenderRemoved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AllowedSourceDomainSenderRemoved.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AllowedSourceDomainSenderRemoved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllowedSourceDomainSenderRemoved.Merge(m, src)
}
func (m *AllowedSourceDomainSenderRemoved) XXX_Size() int {
	return m.Size()
}
func (m *AllowedSourceDomainSenderRemoved) XXX_DiscardUnknown() {
	xxx_messageInfo_AllowedSourceDomainSenderRemoved.DiscardUnknown(m)
}

var xxx_messageInfo_AllowedSourceDomainSenderRemoved proto.InternalMessageInfo

func (m *AllowedSourceDomainSenderRemoved) GetDomain() uint32 {
	if m != nil {
		return m.Domain
	}
	return 0
}

func (m *AllowedSourceDomainSenderRemoved) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func init() {
	proto.RegisterType((*OwnerUpdated)(nil), "noble.router.OwnerUpdated")
	proto.RegisterType((*AllowedSourceDomainSenderAdded)(nil), "noble.router.AllowedSourceDomainSenderAdded")
	proto.RegisterType((*AllowedSourceDomainSenderRemoved)(nil), "noble.router.AllowedSourceDomainSenderRemoved")
}

func init() { proto.RegisterFile("router/events.proto", fileDescriptor_ba99373efa5638de) }

var fileDescriptor_ba99373efa5638de = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0x31, 0x4b, 0xc3, 0x40,
	0x14, 0xc7, 0x13, 0x87, 0x6a, 0x8f, 0xd4, 0x21, 0x8a, 0x14, 0x85, 0xa3, 0x04, 0x04, 0x97, 0x26,
	0x83, 0xa3, 0x53, 0xc5, 0x5d, 0xb8, 0xda, 0xc5, 0x45, 0x92, 0xde, 0x23, 0x06, 0x92, 0x7b, 0xe1,
	0xdd, 0x5d, 0xa2, 0xdf, 0xc2, 0x8f, 0xe5, 0xd8, 0xd1, 0x51, 0x92, 0x2f, 0x22, 0xb9, 0xa6, 0xa3,
	0x4b, 0xb7, 0xf7, 0xfe, 0xff, 0x3f, 0xbf, 0xe1, 0xc7, 0x2e, 0x08, 0xad, 0x01, 0x4a, 0xa0, 0x01,
	0x65, 0x74, 0x5c, 0x13, 0x1a, 0x0c, 0x03, 0x85, 0x59, 0x09, 0xf1, 0xbe, 0xba, 0xbe, 0xcc, 0x31,
	0x47, 0x57, 0x24, 0xc3, 0xb5, 0xdf, 0x44, 0x82, 0x05, 0xcf, 0xad, 0x02, 0xda, 0xd4, 0x32, 0x35,
	0x20, 0xc3, 0x5b, 0x76, 0x5e, 0x13, 0x34, 0x05, 0x5a, 0xfd, 0x86, 0x43, 0x31, 0xf7, 0x17, 0xfe,
	0xdd, 0x54, 0xcc, 0x0e, 0xa9, 0x5b, 0x87, 0x37, 0x6c, 0xaa, 0xa0, 0x1d, 0x17, 0x27, 0x6e, 0x71,
	0xa6, 0xa0, 0x75, 0x65, 0x24, 0x18, 0x5f, 0x95, 0x25, 0xb6, 0x20, 0xd7, 0x68, 0x69, 0x0b, 0x4f,
	0x58, 0xa5, 0x85, 0x5a, 0x83, 0x92, 0x40, 0x2b, 0x29, 0x41, 0x86, 0x57, 0x6c, 0x22, 0x5d, 0xe8,
	0xe8, 0x33, 0x31, 0x7e, 0xe1, 0x9c, 0x9d, 0xa6, 0x52, 0x12, 0x68, 0xed, 0xa0, 0x81, 0x38, 0xbc,
	0xd1, 0x0b, 0x5b, 0xfc, 0xcb, 0x14, 0x50, 0x61, 0x73, 0x0c, 0xf5, 0x71, 0xf3, 0xdd, 0x71, 0x7f,
	0xd7, 0x71, 0xff, 0xb7, 0xe3, 0xfe, 0x57, 0xcf, 0xbd, 0x5d, 0xcf, 0xbd, 0x9f, 0x9e, 0x7b, 0xaf,
	0x0f, 0x79, 0x61, 0xde, 0x6d, 0x16, 0x6f, 0xb1, 0x4a, 0xb4, 0xa1, 0x54, 0xe5, 0x50, 0x62, 0x03,
	0xcb, 0xc1, 0xaf, 0x25, 0xd0, 0x89, 0x73, 0xbb, 0x1c, 0xb5, 0x7f, 0x24, 0xe3, 0x61, 0x3e, 0x6b,
	0xd0, 0xd9, 0xc4, 0xb9, 0xbd, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x2e, 0xb9, 0xb3, 0xc7, 0x96,
	0x01, 0x00, 0x00,
}

func (m *OwnerUpdated) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OwnerUpdated) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OwnerUpdated) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NewOwner) > 0 {
		i -= len(m.NewOwner)
		copy(dAtA[i:], m.NewOwner)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.NewOwner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.PreviousOwner) > 0 {
		i -= len(m.PreviousOwner)
		copy(dAtA[i:], m.PreviousOwner)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.PreviousOwner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AllowedSourceDomainSenderAdded) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AllowedSourceDomainSenderAdded) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AllowedSourceDomainSenderAdded) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if m.Domain != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Domain))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *AllowedSourceDomainSenderRemoved) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AllowedSourceDomainSenderRemoved) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AllowedSourceDomainSenderRemoved) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x12
	}
	if m.Domain != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.Domain))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OwnerUpdated) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PreviousOwner)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	l = len(m.NewOwner)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *AllowedSourceDomainSenderAdded) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Domain != 0 {
		n += 1 + sovEvents(uint64(m.Domain))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func (m *AllowedSourceDomainSenderRemoved) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Domain != 0 {
		n += 1 + sovEvents(uint64(m.Domain))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OwnerUpdated) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OwnerUpdated: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OwnerUpdated: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousOwner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PreviousOwner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewOwner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NewOwner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AllowedSourceDomainSenderAdded) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AllowedSourceDomainSenderAdded: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AllowedSourceDomainSenderAdded: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			m.Domain = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Domain |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = append(m.Address[:0], dAtA[iNdEx:postIndex]...)
			if m.Address == nil {
				m.Address = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AllowedSourceDomainSenderRemoved) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AllowedSourceDomainSenderRemoved: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AllowedSourceDomainSenderRemoved: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			m.Domain = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Domain |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = append(m.Address[:0], dAtA[iNdEx:postIndex]...)
			if m.Address == nil {
				m.Address = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
